name: Codecov Report

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven and generate coverage report
      run: mvn clean test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./target/site/jacoco/jacoco.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}